/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TaskId = IDL.Nat;
export const Task = IDL.Record({ 'id' : TaskId, 'title' : IDL.Text });

export const idlService = IDL.Service({
  'addTask' : IDL.Func([IDL.Text], [Task], []),
  'deleteTask' : IDL.Func([TaskId], [], []),
  'listTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TaskId = IDL.Nat;
  const Task = IDL.Record({ 'id' : TaskId, 'title' : IDL.Text });
  
  return IDL.Service({
    'addTask' : IDL.Func([IDL.Text], [Task], []),
    'deleteTask' : IDL.Func([TaskId], [], []),
    'listTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };